### ISSUE TITLE
Android Support

### ISSUE THREAD

**Issue by arianaa30** [tnomedialab/dash-srd.js#2]
Just a follow-up question on my previous question. Just one minute thought if we can implement an Android SRD player. Do you think it is feasible?! How can we do that? 
The way it works is to run multiple mediaPlayers at the same time, right? So basically an ideal scenario can be to have a mother MediaPlayer that embeds multiple media players as children. And of course they should all be synced and no bordering issues. I just can't think of it.

**Comment by JorritvandenBerg** [comment]
We have no experience with a native Android application for DASH-SRD. There are people that have looked into playing multiple videos simultaneously with MediaPlayer (http://stackoverflow.com/questions/9834882/how-to-play-multiple-video-files-simultaneously-in-one-layout-side-by-side-in-di/20370974#20370974). But this player does not support DASH. ExoPlayer (https://google.github.io/ExoPlayer/) is a project with DASH support.

**Comment by arianaa30** [comment]
Yes, it doesn't support streaming, but at least we get a demo of how it can look. Later maybe we can replace the media player with Exoplayer hopefully if has similar APIs.
